### ISSUE TITLE
FSharp branch

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [cecilphillip/ZeroToHeroDaprCon#1]
if you'd like an FSharp version of this repo, create one and I can PR into it. It seems I there isn't a way for me to PR a new branch into your repo, and I have no intention of PRing over top of your branch.

**Comment by ImaginaryDevelopment** [comment]
branch is here, if you'd like to, or rather just browse https://github.com/ImaginaryDevelopment/ZeroToHeroDaprCon/tree/fsharp

**Comment by cecilphillip** [comment]
Done! Create the branch. Feel free to PR to that one
 => https://github.com/cecilphillip/ZeroToHeroDaprCon/tree/fsharp
